### ISSUE TITLE
Project Analysis Issue

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/arcGNAT#23]
# Introduction
There is some discrepancy as to how GNAT should be using Analyses within the Riverscapes project. Specifically, GNAT tires to use analyses to store "Segmented Networks", where multiple versions of the same realization could be segmented at different intervals (or different segmentation parameters) (see Analyses section of: https://github.com/SouthForkResearch/gnat/wiki/GNAT_Project). The products of theses Analyses/Segmented Networks would serve as inputs to many other projects/tools.

# Issues at Hand

1) Riverscapes does not support multiple versions  of the same type of analysis. https://github.com/Riverscapes/Program/issues/4

2) @volkcj mentioned that we might add attributes to the segmented network, and keep this within the GNAT project. This would violate the uniqueness of the `guid` for the network dataset, and does not store that the attribute was added to the network within the project context.

3) Philip indicated that attribues should be added to the same line network (physical dataset?). The divergence of datasets created by capturing segmentation at the analysis level moves away from this.

# Options/Proposals
While it did make some sense to store segmented networks at the analysis level, it is probably worth rethinking how the GNAT project is structured, at least the latter half.  What we really need to think about is how GNAT is trying to keep the "family history" of the line network, and how each of the geomorphic attributes are related. In other words, what is GNAT trying to keep track of?

**Comment by MattReimer** [comment]
As we discussed on the call, I think we can solve this problem (in the XML) anyway by considering the group of SegmentedNetworks to be the "Analysis". Then you just need to consider what the grouping of networks is. 

Something like:

``` xml
            <Analyses>
                <SegmentedNetworks>
                    
                    <SegmentedNetwork>
                        <segmentsize>2.0</segmentsize>
                        <remainder>0.2</remainder>
                    </SegmentedNetwork>

                    <SegmentedNetwork>
                        <segmentsize>3.0</segmentsize>
                        <remainder>0.4</remainder>
                    </SegmentedNetwork>

                    <SegmentedNetwork>
                        <segmentsize>4.0</segmentsize>
                        <remainder>0.5</remainder>
                    </SegmentedNetwork>

                    <SegmentedNetwork>
                        <segmentsize>5.0</segmentsize>
                        <remainder>0.23423</remainder>
                    </SegmentedNetwork>

                </SegmentedNetworks>
```

This is all with the understanding that if you were asked to "run GNat again please" you would produce a different Realization with a different group of SegmentedNetworks.

**Comment by jesselangdon** [comment]
This is no longer an issue, due to refactoring and the development of the Riverscapes module.
