### ISSUE TITLE
networkVrtx not generated in Build Network Topology Tool

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/arcGNAT#34]
Ran a 1000m segmented network through the Build Network Topology Tool using GNAT version 2.1.06. It appears the networkVrtx table was still not generated (based on the dissolving in-memory data at the end); the Topology network "run 01" successfully generated as well as the Stream Network Table.

![screenshot 2017-05-30 14 31 49](https://cloud.githubusercontent.com/assets/25061462/26605958/db72bbf6-4544-11e7-849b-67fcbcbecdaf.png)

**Comment by aagervasi** [comment]
Actually, this is not true... the Network Vertex table is generated, but by default it writes the output into the same folder as the toolbox. Perhaps add a feature in the future to choose the location of the output?

Thanks!

**Comment by jesselangdon** [comment]
Fixed this issue with:

31215d00015c0fafd79f2fb948516f32031c7b89
