### ISSUE TITLE
Non-urgent: Bad auto-fill of outputs in Stream Sinuosity and Planform Tool

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/arcGNAT#43]
Suggest either removing or changing the auto-fill of outputs in Stream Sinuosity and Planform Tool. At the moment it is currently filling out the 3 outputs (stream sinuosity, valley CL sinuosity, and planform polylines) as the same file name:
![auto-fill_orig](https://user-images.githubusercontent.com/25061462/29328901-f0e635a8-81a8-11e7-86a1-af93484f2a61.png)

To create them as 3 separate polyline outputs with a desired naming scheme and file location, I edited to:
![auto-fill_edit](https://user-images.githubusercontent.com/25061462/29328922-08a8361e-81a9-11e7-9d1d-dbede10ffc5f.png)

**Comment by jesselangdon** [comment]
I added the suggested file names as defaults, but this only works if these parameters are set to 'Optional' which I don't understand.  Must have to do with the internal validation?  This is a bit of a hack for now...

See commit https://github.com/Riverscapes/arcGNAT/commit/4543a25d8ca92a5750f3b1e082c61a3b30645738
