### ISSUE TITLE
What do you want this site called?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/arcGNAT#44]
Hi @volkcj  & @KellyMWhitehead ,
I can hook up your subdomain on this. What do you want it called? Just `gnat.riverscapes.xyz` or something else?

**Comment by jesselangdon** [comment]
I vote for `gnat.riverscapes.xyz`.

**Comment by volkcj** [comment]
gnat.riverscapes.xyz works.  @joewheaton  thanks!

**Comment by KellyMWhitehead** [comment]
Make it so.

**Comment by jesselangdon** [comment]
The riverscapes jekyll template is missing when viewing the documentation on the new domain.

**Comment by jesselangdon** [comment]
This gnat documentation page is fixed.
