### ISSUE TITLE
Centerline Tool generates blank feature

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/arcGNAT#47]
Ran Centerline Tool with GNAT v 2.1.12 with the following inputs and settings and received a blank centerline output. There were no error messages in the results messages. The Valley Bottom input was a single part, single feature. I've included the inputs (VB and stream network) and the output (blank Valley Bottom Centerline feature class) in the data below.

![vbcenterline_error](https://user-images.githubusercontent.com/25061462/31839695-1b9b831c-b597-11e7-8131-d52a61017db3.png)

![vbcenterline_error_results](https://user-images.githubusercontent.com/25061462/31839861-c424a806-b597-11e7-8d28-076f59740a53.png)

Data: 
[ValleyBottomCenterline.zip](https://github.com/Riverscapes/arcGNAT/files/1403144/ValleyBottomCenterline.zip)

**Comment by jesselangdon** [comment]
Unable to recreate the error.
