### ISSUE TITLE
Sinuosity and Planform Tool missing the Sinuosity/Planform outputs

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/arcGNAT#49]
GNAT v 2.3.0 Step 3 > Stream Sinuosity and Planform Tool.
Only output generated is Valley Bottom Centerline with Sinuosity attribute. Missing the Segmented Network with Sinuosity and Segmented Network with Planform attributes.

![gnattool2 3issue_inputs](https://user-images.githubusercontent.com/25061462/31971591-4f6396a2-b8d1-11e7-8501-f0110959f994.png)

![gnattool2 3issue](https://user-images.githubusercontent.com/25061462/31971439-b5ce502c-b8d0-11e7-8557-2abf53a8dc7a.png)

**Comment by jesselangdon** [comment]
These values are now added as new attribute fields to the input stream network feature class.
