### ISSUE TITLE
GNAT Riverscapes xml writing bad output path for segmented networks 

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/arcGNAT#50]
Xml files store segmented network path as <Path>Outputs\ [RealizationName] \Analyses\ [AnalysisName] \SegmentedNetwork.shp\SegmentedNetwork.shp</Path>

Though they are actually stored as: Outputs\ [RealizationName] \Analyses\
 [AnalysisName] \SegmentedNetwork.shp

Discovered this issue in version 2.3.1--unsure yet how many versions back this issue goes.

![inkedgnatriverscapes_xml_issue_li](https://user-images.githubusercontent.com/25061462/32072126-579d9d60-ba46-11e7-8008-c873e0b63624.jpg)

**Comment by jesselangdon** [comment]
The segmented networks shapefile path was being incorrectly parsed. Fixed with commit https://github.com/Riverscapes/arcGNAT/commit/19e4a3af0dace2547c7c7eb79aeb47c390dd3b56.
