### ISSUE TITLE
Conflict between Segmentation Naming Convention in Output compared to Tool Parameters

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/arcGNAT#51]
GNAT V. 2.3.2

The output of the segmentation now correctly creates write the folder output as Outputs\ [RealizationName] \Analyses \[AnalysisName] \SegmentedNetwork in the xml to match the output folder creation.

However, while the naming convention of the output was changed from "GNAT_SegmentedNetwork" to "SegmentedNetwork" in this version of the tool, the tool parameters appear to still be searching for "GNAT_SegmentedNetwork"

![gnat_2 3 2_segmentednetworkissue_1](https://user-images.githubusercontent.com/25061462/32237903-7125cb64-be23-11e7-99e0-30812d212143.png)

![gnat_2 3 2_segmentednetworkissue_2](https://user-images.githubusercontent.com/25061462/32237909-757fbbe8-be23-11e7-9487-1830d5156add.png)

**Comment by jesselangdon** [comment]
Fixed this with a series of changes, but the latest commit is here: https://github.com/Riverscapes/arcGNAT/commit/19e4a3af0dace2547c7c7eb79aeb47c390dd3b56
