### ISSUE TITLE
Please add additional Riverscapes functionality to calculate just Sinuosity

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/arcGNAT#52]
If it's not too much trouble, would you be able to modify the tool so that the option to calculate just Sinuosity is included in the Step 3 toolset, with the ability to create and write a Riverscapes project?

There are several watersheds where I won't have time to calculate Planform, because it requires a lot of editing to the valley bottom polygon; however I'd still like to be able to calculate Sinuosity and put that up on Riverscapes as an attribute analysis.

Thanks!

**Comment by jesselangdon** [comment]
Is just using the **Utilities>Sinuosity by Stream Segment** tool an option?

**Comment by aagervasi** [comment]
For now I am only trying to run GNAT tools where I will be able to upload the outputs into Riverscapes.

**Comment by jesselangdon** [comment]
So I think the best thing to do at this point is to separate the Sinousity from the Planform tool, and have two separate tools under **Analyze Network Attributes > Step 3 - Geomorphic Attributes**.

While this is relatively easy on the front end, it will take some re-jiggering with the Riverscapes functionality.  Although going this route will result in cleaner Riverscapes code.

**Comment by jesselangdon** [comment]
**The Stream Sinuosity and Planform** tool has been reconfigured into two new, separate tools - **Channel Sinuosity** and **Valley Planform**.
