### ISSUE TITLE
Stream Sinuosity and Planform fails unless Output Valley Centerline is assigned

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/arcGNAT#53]
The Stream Sinuosity and Planform tool fails unless an "optional" Valley Centerline with Sinuosity attribute output is assigned and generated (in addition to the one generated in the Riverscapes workspace). A quick fix would be just to take away the "optional" designation in the tool description.

Thanks!

**Comment by jesselangdon** [comment]
Changed valley centerline feature class output from 'optional' to 'required'.
See commit #https://github.com/Riverscapes/arcGNAT/commit/daf293df65a18341ccdbf5565942eed2c14dc965
