### ISSUE TITLE
Valley Planform Tool Error

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/arcGNAT#54]
GNAT v. 2.3.7
![screenshot 2017-11-28 10 39 38](https://user-images.githubusercontent.com/25061462/33337740-ca0940b0-d428-11e7-98bb-96336e3983cb.png)

**Comment by aagervasi** [comment]
Attempted running for both a SegmentedNetwork where the Channel Sinuosity had already been calculated with the Channel Sinuosity Tool and a Segmented Network that did not have the Channel Sinuosity calculated and received the same message.

**Comment by jesselangdon** [comment]
Fixed this issue, and encountered another related issue with how sinuosity attributes were being handled. 

See commit https://github.com/Riverscapes/arcGNAT/commit/82bacc92650ecc99f0c500784a7ba64b35f1eafc for more details.
