### ISSUE TITLE
Analysis Name change causing errors

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/arcGNAT#57]
StreamNetwork dataset tag was changed to GNAT_StreamNetwork is causing some pyt code issues when trying to find datasets.

**Comment by KellyMWhitehead** [comment]
i.e. sinuosity, planform, threadedness tools.

**Comment by jesselangdon** [comment]
Can you elaborate on this?  I'm not sure what you're referring to.  Are you doing some testing of the geomorphic attribute tools?
