### ISSUE TITLE
Planform Tool Error

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/arcGNAT#58]
GNAT v.2.3.8
Now the Planform Tool will run to completion with xml code generated for both Sinuosity and Planform, but nothing is being generated (no additional fields) in the SegmentedNetwork when Planform is run. Please see attached GNAT_Riverscapes project below where both Sinuosity and Planform were run with the latest version for SegmentedNetworks (200m, 500m, 1000m).

Additionally, I noticed in the xml, the "V_Sin" field parameter is called "ChannelSinuosity" I believe this parameter should be called "ValleySinuosity".
Lastly, I'm not sure if this is important, but the actual Gradient field output in the SegmentedNetwork feature class is called "GRADIENT", but it is not capitalized in the xml.

[GNAT2.3.8_SinPlanRun.zip](https://github.com/Riverscapes/arcGNAT/files/1511995/GNAT2.3.8_SinPlanRun.zip)

**Comment by aagervasi** [comment]
![screenshot 2017-11-28 15 52 03](https://user-images.githubusercontent.com/25061462/33350622-a0dee0e2-d454-11e7-8a0e-00490a32d7a0.png)

![inkedscreenshot 2017-11-28 15 50 17_li](https://user-images.githubusercontent.com/25061462/33350616-991244a8-d454-11e7-989c-3e62e1142e99.jpg)

**Comment by aagervasi** [comment]
Actually I guess V_Sin, used to be C_Sin in the old tool when they were combined, so maybe the parameter needs to be removed. This is what the output looked like when the Sinuosity and Planform tools were still combined:

![inkedscreenshot 2017-11-28 16 00 01_li](https://user-images.githubusercontent.com/25061462/33350807-9b85d366-d455-11e7-9249-6e9685cd67bd.jpg)

**Comment by jesselangdon** [comment]
There isn't actually an error occurring here.  The planform and valley sinuosity is not being added back to the input segmentednetwork.shp file on purpose.  The 'V_Sin' and 'Planform' fields _are_ being added to the shapefile that is specified in "Output Valley Centerline with Planform Attribute" field of the form.  These shapefile outputs are also copied to GeomorphicAttributes folder.

So the question is, do we want to the valley sinuosity (V_Sin) and planform attributes added back to the input stream network (as we do in the other geomorphic attribute tools)?  If so, then I need to revise this tool again (for  I think the third or fourth time now)...  and the output shapefile should probably be dropped.  This will take a redesign of the underlying code again as well.
