### ISSUE TITLE
Find Subnetworks failure

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/arcGNAT#71]
Failure occurring for Wenatchee NHD (EP/Perennial only) network both with and without canals removed. GNAT Version 2.4.1

![screenshot 2018-01-31 11 38 20](https://user-images.githubusercontent.com/25061462/35646102-f2340214-0682-11e8-9bd9-6954af2dbc2e.png)

**Comment by jesselangdon** [comment]
Adding a GDAL_DRIVER_PATH environmental variable (which pointed to "C:\Program Files (x86)\GDAL\gdalplugins") seemed to be causing GDAL to malfuntion on Condor.  Removing that environmental variable from Windows 10 seems to have solved the problem.

**Comment by Hornbydd** [comment]
Ahhh! @jesselangdon  I have literally **wasted 5 hours of my life** trying to debug the code to get this tool working. I followed your instructions word for word from [here](http://gnat.riverscapes.xyz/GDAL-install). Step 3 tells you to put in this environment variable! Please update your install instructions so other don't waste hours of their life! I'm using Windows 8.1 with ArcGIS 10.6.

**Comment by jesselangdon** [comment]
@Hornbydd: sorry you had so many problems with the tool.  I no longer work for SFR, so at this point the time I can spend on this tool is minimal.  Setting up GDAL on a Windows machine with ArcGIS installed is definitely not ideal.  I obviously forgot to remove this step from the walkthrough... my apologies.

I've removed step 3.6 from the walkthrough.  Please see commit  # 97345e07bdf2d3a056f050957abbfee627a86241.
