### ISSUE TITLE
Stream Order tool failure

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/arcGNAT#72]
GNAT version 2.4.1.

Used the Wenatchee network, which was cleaned and run through an old version of GNAT (pre-2.4) to prepare for segmentation. Receiving the error below. It looks like the intermediate dissolved file has an invalid name.

![screenshot 2018-01-31 13 04 36](https://user-images.githubusercontent.com/25061462/35648314-305a9952-068a-11e8-93e7-1bfcf1a49811.png)

**Comment by jesselangdon** [comment]
You must run the network through the first two tools - Find Subnetworks and Generate Network Attributes - before running this tool.  There are attribute fields that need to be present for the stream order tool to work.
