### ISSUE TITLE
TheissanPolyClip does not exist or is not supported

### ISSUE THREAD

**Issue by aagervasi** [Riverscapes/arcGNAT#74]
GNAT 2.5.1, ArcGIS 10.4.

I am encountering an issue while trying to transfer the ReachCode between an old and new 24K NHD Flowline. Layers have Z and M values disabled. They are in the same projected coordinate system (NAD_1983_UTM_Zone_11N). both networks are segmented.

The screenshot below shows the error message I am encountering.
![screenshot 2018-03-02 16 49 44](https://user-images.githubusercontent.com/25061462/36994202-38c2c534-2065-11e8-8571-16b35a3de287.png)

**Comment by aagervasi** [comment]
[TLAscratch.gdb.zip](https://github.com/Riverscapes/arcGNAT/files/1782469/TLAscratch.gdb.zip)

**Comment by jesselangdon** [comment]
There was an issue with the 'From' buffer polygon having geometry/topology errors, which caused a subsequent error when clipping the theissen polygons.  

Fixed with commit #https://github.com/Riverscapes/arcGNAT/commit/ae9adfeb2c2675e951197ed01f6a48e2e7efe2de
