### ISSUE TITLE
No module named Riverscapes

### ISSUE THREAD

**Issue by jesselangdon** [Riverscapes/arcGNAT#75]
I just installed the latest commit (#6d93f80) on Merlin, and there seems to be an issue with the Riverscapes module.  When attempting to run 'Create a New GNAT Project', I get the following error message:

![image](https://user-images.githubusercontent.com/2524993/38527571-478b7856-3c10-11e8-91e2-e15ef7528fbb.png)

**Comment by KellyMWhitehead** [comment]
Make sure the submodule Riverscapes exists in the project folder. I think submodules need to be pulled separately if a repo is first cloned to a local computer.
