### ISSUE TITLE
Generate Network Attributes tool GNIS_Name error

### ISSUE THREAD

**Issue by volkcj** [Riverscapes/arcGNAT#76]
Ran Find Subnetworks tool (there were subnetworks)
Ran output from Find Subnetworks tool through Generate Network Attributes tool (the input file is attached).  Note that canals were removed and GNIS_NAME exist in the file.
![2018-04-18_160859](https://user-images.githubusercontent.com/13526689/38962664-2e60018e-4323-11e8-82d4-3c2ff3249af4.png)

**Comment by jesselangdon** [comment]
Currently the attribute field - "GNIS_Name" is hard-coded into the tool.  I need to add an input parameter that allows the user to select the "GNIS Name" or "stream name" attribute field, and make it a requirement.

**Comment by jesselangdon** [comment]
See commit # e98457dd7a8f4d2c5f7ff1225a0f71f2b6a9bcc6
