### ISSUE TITLE
Find Subnetworks bug 

### ISSUE THREAD

**Issue by volkcj** [Riverscapes/arcGNAT#78]
I ran the 1:100k NHDPlus network clipped to the Methow (and no canals) through the subnetwork tool and got this error.  
![2018-04-20_170945](https://user-images.githubusercontent.com/13526689/39078343-f458a45e-44bd-11e8-967e-0729f9ad98ba.png)

**Comment by jesselangdon** [comment]
Is this the projected dataset I just sent you earlier?

**Comment by jesselangdon** [comment]
Added function in updateMessages function of tool class in GNAT.pyt to check for M-values.  An error is now returned if the geometry values are 'Polyline MZ'.

See commit https://github.com/Riverscapes/arcGNAT/commit/a88c280c107f356751ca76786d7603a54f3fda7f
