### ISSUE TITLE
2.6 Strahler Order error

### ISSUE THREAD

**Issue by volkcj** [Riverscapes/arcGNAT#83]
Here's the error and the input file.  I did select a temporary workspace.  

![2018-04-25_154914](https://user-images.githubusercontent.com/13526689/39277015-9556f46a-48a0-11e8-9990-89336c8dfa56.png)
[NHD_A_1p3_GenNetAtt_prj.zip](https://github.com/Riverscapes/arcGNAT/files/1949087/NHD_A_1p3_GenNetAtt_prj.zip)

**Comment by jesselangdon** [comment]
See commit https://github.com/Riverscapes/arcGNAT/commit/a9a598f5f7da69c25d91f63dad05e33ba3ae34da for details.

**Comment by Hornbydd** [comment]
@jesselangdon This error and your subsequent fix has not made it into the download version which one downloads from here: http://gnat.riverscapes.xyz/releases. This is what I had downloaded from the official website, so the generate strahler order tool is still broken for non-programmers. I was able to splice in your edits to get it going
